---
kind: Service
apiVersion: v1
metadata:
  name: minikube-service
  namespace: default
spec:
  selector:
    app: minikube-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
